[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-GB"
    footer = 'Written by <a class="text-muted" href="https://www.linkedin.com/in/brandon-maytham/">Brandon Maytham</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
