name = "Doks"
license = "MIT"
licenselink = "https://github.com/thuliteio/doks/blob/master/LICENSE"
description = "Build beautiful, high-performance documentation websites with Doks."

homepage = "https://docs.securehive.co.uk"
demosite = "https://securehive.netlify.app"

tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["secure by design", "fast by default", "search optimized", "full text search", "page layouts", "dark mode"]

[author]
  name = "Brandon Maytham"
  homepage = "hhttps://uk.linkedin.com/in/brandon-maytham-0b3310144"
